const header=document.querySelector('[data-header]');const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('#site-nav');
const closeMenu=()=>{nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')};
menu?.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(isOpen))});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;let ticking=false;window.addEventListener('scroll',()=>{header?.classList.toggle('scrolled',window.scrollY>24);if(!reduceMotion&&!ticking){requestAnimationFrame(()=>{document.documentElement.style.setProperty('--scroll',String(Math.min(window.scrollY/window.innerHeight,1)));ticking=false});ticking=true}},{passive:true});
if('IntersectionObserver' in window&&!reduceMotion){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element))}else{document.querySelectorAll('.reveal').forEach(element=>element.classList.add('visible'))}
const parallax=document.querySelector('[data-parallax]');if(parallax&&!reduceMotion){parallax.addEventListener('pointermove',event=>{const box=parallax.getBoundingClientRect();const x=(event.clientX-box.left)/box.width-.5;const y=(event.clientY-box.top)/box.height-.5;parallax.style.setProperty('--tilt-x',`${x*7}deg`);parallax.style.setProperty('--tilt-y',`${y*-7}deg`)});parallax.addEventListener('pointerleave',()=>{parallax.style.setProperty('--tilt-x','0deg');parallax.style.setProperty('--tilt-y','0deg')})}
const vessel=document.querySelector('[data-vessel]');if(vessel){const books={"meat-wagon":{kicker:"THE BOOK THAT BEGAN THE CROSSING",title:"Meat Wagon",copy:"Humanity got healthier. Then somebody noticed we tasted better.",buy:"https://www.amazon.com/dp/B0HCWJWTZZ",explore:"books/meat-wagon/"},"ocala-nine":{kicker:"DARK LEGEND · NEW FROM 36SEAS",title:"The Ocala Nine",copy:"The fountain was found. Nine paid the price.",buy:"https://www.amazon.com/dp/B0H18PZSY9",explore:"books/the-ocala-nine/"}};let activeBook="meat-wagon",bookTimer,bookPaused=false;const setBook=id=>{const book=books[id];if(!book)return;activeBook=id;vessel.dataset.activeBook=id;vessel.classList.toggle('is-meat-wagon',id==='meat-wagon');vessel.classList.toggle('is-ocala-nine',id==='ocala-nine');vessel.querySelectorAll('[data-cover]').forEach(el=>el.classList.toggle('is-active',el.dataset.cover===id));vessel.querySelectorAll('[data-book-button]').forEach(el=>{const on=el.dataset.bookButton===id;el.classList.toggle('is-active',on);el.setAttribute('aria-pressed',String(on))});vessel.querySelector('[data-book-kicker]').textContent=book.kicker;vessel.querySelector('[data-book-title]').textContent=book.title;vessel.querySelector('[data-book-copy]').textContent=book.copy;vessel.querySelector('[data-book-buy]').href=book.buy;vessel.querySelector('[data-book-explore]').href=book.explore};const cycleBooks=()=>{if(!bookPaused)setBook(activeBook==='meat-wagon'?'ocala-nine':'meat-wagon')};if(!reduceMotion)bookTimer=setInterval(cycleBooks,6200);vessel.querySelectorAll('[data-book-button]').forEach(button=>button.addEventListener('click',()=>{bookPaused=true;setBook(button.dataset.bookButton);clearInterval(bookTimer)}));vessel.addEventListener('pointerenter',()=>{bookPaused=true});vessel.addEventListener('pointerleave',()=>{bookPaused=false});if(!reduceMotion){vessel.addEventListener('pointermove',event=>{const box=vessel.getBoundingClientRect();const x=(event.clientX-box.left)/box.width-.5;const y=(event.clientY-box.top)/box.height-.5;vessel.style.setProperty('--vessel-y',`${-13+x*6}deg`);vessel.style.setProperty('--vessel-x',`${3-y*3}deg`)});vessel.addEventListener('pointerleave',()=>{vessel.style.setProperty('--vessel-y','-13deg');vessel.style.setProperty('--vessel-x','3deg')});let motionTick=false;window.addEventListener('scroll',()=>{if(!motionTick){requestAnimationFrame(()=>{const hero=document.querySelector('.origin-hero');const progress=Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/Math.max(hero.offsetHeight*.78,1)));vessel.style.setProperty('--hero-scroll',progress.toFixed(4));motionTick=false});motionTick=true}},{passive:true})}}
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
