const header=document.querySelector('[data-header]');const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('#site-nav');
const closeMenu=()=>{nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')};
menu?.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(isOpen))});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;let ticking=false;window.addEventListener('scroll',()=>{header?.classList.toggle('scrolled',window.scrollY>24);if(!reduceMotion&&!ticking){requestAnimationFrame(()=>{document.documentElement.style.setProperty('--scroll',String(Math.min(window.scrollY/window.innerHeight,1)));ticking=false});ticking=true}},{passive:true});
if('IntersectionObserver' in window&&!reduceMotion){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element))}else{document.querySelectorAll('.reveal').forEach(element=>element.classList.add('visible'))}
const parallax=document.querySelector('[data-parallax]');if(parallax&&!reduceMotion){parallax.addEventListener('pointermove',event=>{const box=parallax.getBoundingClientRect();const x=(event.clientX-box.left)/box.width-.5;const y=(event.clientY-box.top)/box.height-.5;parallax.style.setProperty('--tilt-x',`${x*7}deg`);parallax.style.setProperty('--tilt-y',`${y*-7}deg`)});parallax.addEventListener('pointerleave',()=>{parallax.style.setProperty('--tilt-x','0deg');parallax.style.setProperty('--tilt-y','0deg')})}
const flipBook=document.querySelector('[data-flip-book]');const flipControl=document.querySelector('[data-flip-control]');const toggleBook=()=>{const flipped=flipBook?.classList.toggle('is-flipped')??false;flipBook?.setAttribute('aria-pressed',String(flipped));flipBook?.setAttribute('aria-label',flipped?'Show the front cover of Meat Wagon':'Show the back cover of Meat Wagon');if(flipControl)flipControl.childNodes[0].textContent=flipped?'Flip to front cover ':'Flip to back cover '};flipBook?.addEventListener('click',toggleBook);flipControl?.addEventListener('click',toggleBook);
document.getElementById('year').textContent=new Date().getFullYear();
